// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendsDemo.Models;

namespace SpendsDemo.Migrations
{
    [DbContext(typeof(SpendsContext))]
    partial class SpendsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("SpendsDemo.Models.Spends", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdSize");

                    b.Property<string>("Advertizer")
                        .IsRequired();

                    b.Property<int>("AverageDuration");

                    b.Property<string>("Brand")
                        .IsRequired();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("Days")
                        .IsRequired();

                    b.Property<string>("Media")
                        .IsRequired();

                    b.Property<string>("Month")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Print");

                    b.Property<string>("Quarter")
                        .IsRequired();

                    b.Property<string>("Region")
                        .IsRequired();

                    b.Property<string>("Station")
                        .IsRequired();

                    b.Property<int>("TVRadio");

                    b.Property<string>("TimeBand");

                    b.Property<string>("TimeSlot");

                    b.Property<string>("TotalSpend")
                        .IsRequired();

                    b.Property<DateTime>("dateAdded");

                    b.HasKey("Id");

                    b.ToTable("Spends");
                });
#pragma warning restore 612, 618
        }
    }
}
